import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        {/* Sidebar */}
        <aside className="w-1/4 h-screen bg-gray-800 text-white p-4">
          <h1 className="text-lg font-bold mb-6">Dorakart</h1>
          <nav>
            {/* Accordion Items */}
            <AccordionItem title="All products" />
            <AccordionItem title="Orders" />
            <AccordionItem title="Designing" />
            <AccordionItem title="Printing" />
            <AccordionItem title="Shipping" />
          </nav>
        </aside>

        {/* Main Content */}
        <main className="w-3/4 p-8">{children}</main>
      </body>
    </html>
  );
}

// Accordion Item Component
function AccordionItem({ title }) {
  const [isOpen, setIsOpen] = React.useState(false);

  return (
    <div className="mb-4">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={`w-full text-left py-2 px-4 rounded-md ${
          isOpen ? "bg-gray-700" : "bg-gray-600"
        } hover:bg-gray-700`}
      >
        {title}
      </button>
      {isOpen && (
        <div className="mt-2 pl-4 text-sm text-gray-300">
          <p>Content for {title}</p>
        </div>
      )}
    </div>
  );
}
